# ============================================================================
#  .tmux.conf — Configuração do Tmux
# ============================================================================

# Mouse
set -g mouse on

# Início em 1 (não 0)
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Reload config
bind r source-file ~/.tmux.conf \; display "Tmux recarregado!"

# Navegação entre panes (vim-like)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Histórico
set -g history-limit 50000

# Escape time
set -sg escape-time 0
